name:                HsWebots
version:             0.1.1.0
github:              "junjihashimoto/HsWebots"
license:             MIT
author:              "Junji Hashimoto"
maintainer:          "junji.hashimoto@gmail.com"
copyright:           "2020 Junji Hashimoto"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Webots bindings for Haskell
category:            Robotics

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/junjihashimoto/HsWebots#readme>

dependencies:
- base >= 4.7 && < 5
- inline-c-cpp >= 0.4.0.0
- inline-c >= 0.9.0.0
- template-haskell
- JuicyPixels
- vector
- bytestring
- safe-exceptions

library:
  source-dirs: src

executables:
  HsWebots-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HsWebots
    - language-c
    - syb
    - pretty
    - shakespeare
    - text

tests:
  HsWebots-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HsWebots
