name: stack-linux

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Setup packages
      run: |
        sudo add-apt-repository ppa:ubuntu-toolchain-r/test
        sudo apt update -qq
        sudo apt -y --allow-downgrades --allow-remove-essential --allow-change-held-packages install cmake curl wget unzip git libtinfo-dev python3 python3-yaml libxkbcommon-x11-0
        wget -q https://github.com/cyberbotics/webots/releases/download/R2020a-rev1/webots_2020a-rev1_amd64.deb
        sudo apt -y --allow-downgrades --allow-remove-essential --allow-change-held-packages install ./webots_2020a-rev1_amd64.deb
        (wget -qO- https://get.haskellstack.org/ | sh) || true
    - name: Build
      run: |
        . setenv
        stack build
    - name: Test
      run: |
        . setenv
        export AUDIODEV=null
        export DEBIAN_FRONTEND=noninteractive
        export DISPLAY=:99
        export LIBGL_ALWAYS_SOFTWARE=true
        Xvfb :99 -screen 0 1024x768x16 +extension GLX +render -noreset &
        stack test
