name: stack-macos

on: [push, pull_request]

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup tool-chains
      run: |
        /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
        brew install libomp || true
        pip3 install pyyaml || true
        wget -q https://github.com/cyberbotics/webots/releases/download/R2020a-rev1/webots-R2020a-rev1.dmg
        dmgFilePath=`pwd`/webots-R2020a-rev1.dmg
        hdiutil mount $dmgFilePath
        (wget -qO- https://get.haskellstack.org/ | sh) || true
        #installer -pkg /Volumes/Webots/Webots.app -target /Applications
    - name: Build
      run: |
        WEBOTS_HOME=/Volumes/Webots/Webots.app
        . setenv
        stack build
#    ToDo: controller can not load shared library of libController.dylib
#          The controller's command is "stack runghc test/Webots/xx.hs controller".
#    - name: Test
#      run: |
#        WEBOTS_HOME=/Volumes/Webots/Webots.app
#        PATH=$WEBOTS_HOME:$PATH
#        . setenv
#        stack test
