name: stack-macos

on: [push, pull_request]

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup tool-chains
      run: |
        /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
        brew install libomp || true
        pip3 install pyyaml || true
        wget -q https://github.com/cyberbotics/webots/releases/download/R2020a-rev1/webots-R2020a-rev1.dmg
        dmgFilePath=`pwd`/webots-R2020a-rev1.dmg
        MOUNTDIR=$(echo `hdiutil mount $dmgFilePath | tail -1 | awk '{$1=$2=""; print $0}'` | xargs -0 echo)
        sudo installer -pkg "${MOUNTDIR}/"*.pkg -target /
        (wget -qO- https://get.haskellstack.org/ | sh) || true
    - name: Build
      run: |
        . setenv
        stack build
    - name: Test
      run: |
        . setenv
        stack test
